from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage

from .prompt import IMAGE_PROMPT, TEXT_PROMPT_PREFIX , JSON_EXTRACTION_PROMPT ,system_prompt
from .state import AgentState
from dotenv import load_dotenv
from tools import tools
load_dotenv()
llm = ChatOpenAI(model="gpt-4o", temperature=0)


def process_with_llm(state: AgentState):
	content = state["file_content"]

	if state["file_type"] == "image":
		message = HumanMessage(
			content=[
				{"type": "text", "text": IMAGE_PROMPT},
				{"type": "image_url", "image_url": {"url": content}},
			]
		)
	else:
		message = HumanMessage(content=f"{TEXT_PROMPT_PREFIX}{content}")

	response = llm.invoke([message])
	return {"final_output": response.content}




def process_with_agent(state: AgentState):
	content = state["final_output"]

	if state["file_type"] == "image":
		message = HumanMessage(
			content=[
				{"type": "text", "text": IMAGE_PROMPT},
				{"type": "image_url", "image_url": {"url": content}},
			]
		)
	else:
		message = HumanMessage(content=f"{TEXT_PROMPT_PREFIX}{content}")

	response = llm.invoke([message])
	return {"final_output": response.content}



import json
from langchain_core.messages import SystemMessage, HumanMessage

def process_with_agent(state: AgentState):
    # 1. Grab the raw text generated by the FIRST node
    # (Node 1 should save its output to something like state["raw_text"])
    raw_transcription = state["final_output"] 

    # 2. Set up the messages with our new prompt
    messages = [
        SystemMessage(content=JSON_EXTRACTION_PROMPT),
        HumanMessage(content=f"Here is the transcribed exam text to parse:\n\n{raw_transcription}")
    ]

    # 3. Force GPT-4o to return STRICT JSON
    # This is the secret sauce so it doesn't give you markdown like ```json ... ```
    json_llm = llm.bind(response_format={"type": "json_object"})
    
    # 4. Invoke the model
    response = json_llm.invoke(messages)
    
    # 5. Optional: Verify it parsed correctly (Good for debugging)
    try:
        # Check if it's valid JSON
        parsed_json = json.loads(response.content)
        # Convert it back to a pretty string so your API can return it easily
        final_json_string = json.dumps(parsed_json, indent=2) 
    except json.JSONDecodeError:
        final_json_string = json.dumps({"error": "Failed to parse JSON", "raw_output": response.content})

    # 6. Return the beautifully structured JSON string
    return {"final_output": final_json_string}


def save_with_agent(state: AgentState):
	content = state["final_output"]

	message = HumanMessage(content=f"{system_prompt}{content}")

	response = llm.invoke([message])
	return {"final_output": response.content}

from langgraph.prebuilt import ToolNode

tool_node = ToolNode(tools)
