-- 1. Syllabus uploads
CREATE TABLE public.syllabi (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id uuid NOT NULL,
  filename text NOT NULL,
  raw_text text,
  status text NOT NULL DEFAULT 'processing',
  entity_count integer DEFAULT 0,
  relationship_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT syllabi_teacher_fkey FOREIGN KEY (teacher_id) REFERENCES public.users(id)
);

-- 2. Entities extracted from syllabus (with vector embedding)
CREATE TABLE public.syllabus_entities (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  syllabus_id integer NOT NULL,
  name text NOT NULL,
  entity_type text NOT NULL,
  description text,
  difficulty_level text,
  week_or_unit text,
  embedding vector(1536),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT entities_syllabus_fkey FOREIGN KEY (syllabus_id) REFERENCES public.syllabi(id) ON DELETE CASCADE,
  CONSTRAINT unique_entity_per_syllabus UNIQUE (syllabus_id, name)
);

-- 3. Relationships between entities
CREATE TABLE public.syllabus_relationships (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  syllabus_id integer NOT NULL,
  source_entity_id integer NOT NULL,
  target_entity_id integer NOT NULL,
  relationship_type text NOT NULL,
  strength integer DEFAULT 3,
  reason text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT rel_syllabus_fkey FOREIGN KEY (syllabus_id) REFERENCES public.syllabi(id) ON DELETE CASCADE,
  CONSTRAINT rel_source_fkey FOREIGN KEY (source_entity_id) REFERENCES public.syllabus_entities(id) ON DELETE CASCADE,
  CONSTRAINT rel_target_fkey FOREIGN KEY (target_entity_id) REFERENCES public.syllabus_entities(id) ON DELETE CASCADE
);

-- Indexes
CREATE INDEX idx_entities_syllabus ON public.syllabus_entities(syllabus_id);
CREATE INDEX idx_entities_embedding ON public.syllabus_entities USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);
CREATE INDEX idx_relationships_syllabus ON public.syllabus_relationships(syllabus_id);
CREATE INDEX idx_relationships_source ON public.syllabus_relationships(source_entity_id);
CREATE INDEX idx_relationships_target ON public.syllabus_relationships(target_entity_id);
