CREATE TABLE public.student_question_scores (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  teacher_id uuid NOT NULL,
  student_id text NOT NULL,
  assignment_id integer NOT NULL,
  
  question_label text NOT NULL,
  
  -- 
  question_text text,
  student_solution text,
  
  marks numeric NOT NULL DEFAULT 0.0,

  confidence_score numeric NOT NULL,
  

  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),

  -- Prevents duplicate scores for the exact same question label for a single student
  CONSTRAINT unique_student_question_score 
    UNIQUE (assignment_id, student_id, question_label),

  -- Link back to the users table
  CONSTRAINT sqs_teacher_fkey
    FOREIGN KEY (teacher_id)
    REFERENCES public.users(id),

  -- Link back to the composite primary key of the students table
  CONSTRAINT sqs_student_fkey
    FOREIGN KEY (teacher_id, student_id)
    REFERENCES public.students(teacher_id, id),

  -- Link back to the assignment
  CONSTRAINT sqs_assignment_fkey
    FOREIGN KEY (assignment_id)
    REFERENCES public.assignments(id)
);

-- Index to quickly load a specific student's complete scorecard for an assignment
CREATE INDEX idx_student_question_scores_lookup
ON public.student_question_scores(assignment_id, student_id);